export const SET_PRODUCTS = 'SET_PRODUCTS';
export const PRODUCT_SET_LOADING = 'PRODUCT_SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const SET_PRODUCT = 'SET_PRODUCT';
export const PRODUCT_CLEAR_ERROR = 'CLEAR_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const AUTH_CLEAR_ERROR = 'CLEAR_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const GET_SHIPPING_ADDRESSES = 'GET_SHIPPING_ADDRESSES';

export const ORDER_SET_LOADING = 'ORDER_SET_LOADING';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const CLEAR_ORDER_STATE = 'CLEAR_ORDER_STATE';